//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XM.Comm {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReturnResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XM.Comm.ReturnResource", typeof(ReturnResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 game001 的本地化字符串。
        /// </summary>
        internal static string game001 {
            get {
                return ResourceManager.GetString("game001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 game002 的本地化字符串。
        /// </summary>
        internal static string game002 {
            get {
                return ResourceManager.GetString("game002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 game003 的本地化字符串。
        /// </summary>
        internal static string game003 {
            get {
                return ResourceManager.GetString("game003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 game004 的本地化字符串。
        /// </summary>
        internal static string game004 {
            get {
                return ResourceManager.GetString("game004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 game005 的本地化字符串。
        /// </summary>
        internal static string game005 {
            get {
                return ResourceManager.GetString("game005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shop001 的本地化字符串。
        /// </summary>
        internal static string shop001 {
            get {
                return ResourceManager.GetString("shop001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shop002 的本地化字符串。
        /// </summary>
        internal static string shop002 {
            get {
                return ResourceManager.GetString("shop002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip001 的本地化字符串。
        /// </summary>
        internal static string vip001 {
            get {
                return ResourceManager.GetString("vip001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip002 的本地化字符串。
        /// </summary>
        internal static string vip002 {
            get {
                return ResourceManager.GetString("vip002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip003 的本地化字符串。
        /// </summary>
        internal static string vip003 {
            get {
                return ResourceManager.GetString("vip003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip004 的本地化字符串。
        /// </summary>
        internal static string vip004 {
            get {
                return ResourceManager.GetString("vip004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip005 的本地化字符串。
        /// </summary>
        internal static string vip005 {
            get {
                return ResourceManager.GetString("vip005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip006 的本地化字符串。
        /// </summary>
        internal static string vip006 {
            get {
                return ResourceManager.GetString("vip006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip007 的本地化字符串。
        /// </summary>
        internal static string vip007 {
            get {
                return ResourceManager.GetString("vip007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip008 的本地化字符串。
        /// </summary>
        internal static string vip008 {
            get {
                return ResourceManager.GetString("vip008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip009 的本地化字符串。
        /// </summary>
        internal static string vip009 {
            get {
                return ResourceManager.GetString("vip009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip010 的本地化字符串。
        /// </summary>
        internal static string vip010 {
            get {
                return ResourceManager.GetString("vip010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip011 的本地化字符串。
        /// </summary>
        internal static string vip011 {
            get {
                return ResourceManager.GetString("vip011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip012 的本地化字符串。
        /// </summary>
        internal static string vip012 {
            get {
                return ResourceManager.GetString("vip012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip013 的本地化字符串。
        /// </summary>
        internal static string vip013 {
            get {
                return ResourceManager.GetString("vip013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip014 的本地化字符串。
        /// </summary>
        internal static string vip014 {
            get {
                return ResourceManager.GetString("vip014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip015 的本地化字符串。
        /// </summary>
        internal static string vip015 {
            get {
                return ResourceManager.GetString("vip015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip016 的本地化字符串。
        /// </summary>
        internal static string vip016 {
            get {
                return ResourceManager.GetString("vip016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip017 的本地化字符串。
        /// </summary>
        internal static string vip017 {
            get {
                return ResourceManager.GetString("vip017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip018 的本地化字符串。
        /// </summary>
        internal static string vip018 {
            get {
                return ResourceManager.GetString("vip018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip019 的本地化字符串。
        /// </summary>
        internal static string vip019 {
            get {
                return ResourceManager.GetString("vip019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip020 的本地化字符串。
        /// </summary>
        internal static string vip020 {
            get {
                return ResourceManager.GetString("vip020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip021 的本地化字符串。
        /// </summary>
        internal static string vip021 {
            get {
                return ResourceManager.GetString("vip021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip022 的本地化字符串。
        /// </summary>
        internal static string vip022 {
            get {
                return ResourceManager.GetString("vip022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip023 的本地化字符串。
        /// </summary>
        internal static string vip023 {
            get {
                return ResourceManager.GetString("vip023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip024 的本地化字符串。
        /// </summary>
        internal static string vip024 {
            get {
                return ResourceManager.GetString("vip024", resourceCulture);
            }
        }
    }
}
